# Generated by Django 4.1.2 on 2024-09-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='nome_completo',
        ),
    ]
