# Generated by Django 4.1.2 on 2024-09-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='nome_completo',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='endereco_envio',
            new_name='shipping_address',
        ),
    ]
